FROM ubuntu:15.10

MAINTAINER strigidaeinsomnie

RUN apt-get update && \
    apt-get upgrade -y && \

    apt-get install -y python3 python3-dev python3-setuptools python3-pip \
    libxml2-dev libxslt1-dev zlib1g-dev \

    git && \

    pip3 install BeautifulSoup4 lxml && \

    git clone git://github.com/strigidaeinsomnie/inproduction.git
