FROM ubuntu:15.10

MAINTAINER strigidaeinsomnie

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y python python-setuptools python-pip \
    git && \
    pip install github3.py && \
    git clone git://github.com/strigidaeinsomnie/inproduction.git
